### ISSUE TITLE
Error on key 'second' that is sent in 'results' list

### ISSUE THREAD

**Issue by jessicaori** [jpsandovaln/AT2024Progra2MLService#11]
The frames that were analyzed are being returned and do contain the analyzed object/gender, but the `second` key is being sent with an error. Check the `get_time` function of the DetectedFrame class, the frame that is sent to MLService contains in its `filename` the second to which it belongs.

**File to check:** models/Recognizer/DetectedFrame.py
**Lines:** 10, 19
**Response returning to UI:**
![image](https://github.com/user-attachments/assets/bc920320-8d6a-48ea-a014-146a5a93026d)

![image](https://github.com/user-attachments/assets/0b072bdd-2e6e-44ad-bb56-576524ac2ee1)

**Comment by Eynar92** [comment]
## **Fixed**
The value of the 'second' parameter is returned in seconds

- Response in the face_recognition endpoint
```
{
 "algorithm": "DeepFace",
 "path": "/app/uploads/ucexportdownloadid1HbeeHzKfACRbRKomv08HcxKDro9ChaxX/11.jpg",
 "percentage": 36.04,
 "second": "11"
 "word": "person"
}
```
- Response in the recognition endpoint
```
{
  "algorithm": "Yolo11",
  "path": "/app/uploads/ucexportdownloadid1HbeeHzKfACRbRKomv08HcxKDro9ChaxX/1.jpg",
  "percentage": 90.19,
  "second": "1",
  "word": "person"
}
```

**Comment by jessicaori** [comment]
Issue fixed! ⭐
